
package de.wwu.pi.soapadder.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapAdderServiceBeanService", targetNamespace = "http://soapadder.pi.wwu.de/", wsdlLocation = "http://localhost:8080/SoapService/SoapAdderServiceBean?wsdl")
public class SoapAdderServiceBeanService
    extends Service
{

    private final static URL SOAPADDERSERVICEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPADDERSERVICEBEANSERVICE_EXCEPTION;
    private final static QName SOAPADDERSERVICEBEANSERVICE_QNAME = new QName("http://soapadder.pi.wwu.de/", "SoapAdderServiceBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SoapService/SoapAdderServiceBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPADDERSERVICEBEANSERVICE_WSDL_LOCATION = url;
        SOAPADDERSERVICEBEANSERVICE_EXCEPTION = e;
    }

    public SoapAdderServiceBeanService() {
        super(__getWsdlLocation(), SOAPADDERSERVICEBEANSERVICE_QNAME);
    }

    public SoapAdderServiceBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPADDERSERVICEBEANSERVICE_QNAME, features);
    }

    public SoapAdderServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, SOAPADDERSERVICEBEANSERVICE_QNAME);
    }

    public SoapAdderServiceBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPADDERSERVICEBEANSERVICE_QNAME, features);
    }

    public SoapAdderServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapAdderServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapAdderServiceBean
     */
    @WebEndpoint(name = "SoapAdderServiceBeanPort")
    public SoapAdderServiceBean getSoapAdderServiceBeanPort() {
        return super.getPort(new QName("http://soapadder.pi.wwu.de/", "SoapAdderServiceBeanPort"), SoapAdderServiceBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapAdderServiceBean
     */
    @WebEndpoint(name = "SoapAdderServiceBeanPort")
    public SoapAdderServiceBean getSoapAdderServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapadder.pi.wwu.de/", "SoapAdderServiceBeanPort"), SoapAdderServiceBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPADDERSERVICEBEANSERVICE_EXCEPTION!= null) {
            throw SOAPADDERSERVICEBEANSERVICE_EXCEPTION;
        }
        return SOAPADDERSERVICEBEANSERVICE_WSDL_LOCATION;
    }

}
